### PR TITLE
Module teamplayers upgrade

### PR DESCRIPTION
**Pull request by llambion72**
I've added some new features to this module.
Player list can show mins played and players positions and sorted by mins and positions

I've created an alternative template using bxslider. It can show a stickers players card. 
Flag, position, mins played can be enabled or disabled. 
Also it can be configured the number of the players, slider speed, orientation (vertical, horizontal), navigation links and pagination icons.

Pictures below show backend configuration and frontend display.
team_players02
team_players04
team_players01
team_players03

### CODE REVIEW

**Comment by diddipoeler** [comment]
Many thanks.

**Comment by llambion72** [comment]
i'll add more features in the next versions

**Comment by diddipoeler** [comment]
can i register your name in the component as developer/helper ?
can you send me a photo from you ?

**Comment by llambion72** [comment]
You can register my name. My name is Héctor Rodriguez, my nick is Llambion
a picture about me...
many thanks!!

hector

**Comment by diddipoeler** [comment]
your picture can be found in the component.
what do you think about the component ? it´s great or ?

**Comment by llambion72** [comment]
I'd like so much this component. I used it since 10-12 years ago, first as joomleague and now as sportmanagement.
I'm a member of a group of supporters of Real Oviedo team, on spanish second division and every year i create a prediction competition.
Also I use to publish all information about our team. I think that if you like sports this is your component.
I've started to write lines of code more than 30 years ago but i'd never programmed for joomla, it's bit difficult for me but i don't matter spend many hours to improve this component because i'm learning about joomla.
My website is, 
lenayeazul.com
I use sportmanagement allmost everything

**Comment by diddipoeler** [comment]
thanks.
can you write a review here: https://extensions.joomla.org/extension/sports-management/ please ?

**Comment by llambion72** [comment]
Reviewed.
I wrote review in spanish because there isn't any review in spanish.

**Pull request merged**
