### PR TITLE
Update RU

### PR DESCRIPTION
**Pull request by sk-plehanovec**

### CODE REVIEW

**Comment by sigal** [comment]
Translations are taken exclusively from Transifex!
Please make your translation on Transifex!
https://www.transifex.com/jsm/public/

**Comment by diddipoeler** [comment]
is this ok when i merge the request ?

**Comment by sigal** [comment]
No, diidi! 
sk-plehanovec make yet translation on transifex.
I push this translations into GitHub. Than you can merge this in your master branch.

Then we have a uniform structure of all language files.
All new language keys are retrieved directly from Transifex of your GitHub master branch as raw file.
This means that all languages have the same structure.

You can see the status of translated languages on my site as widget from transifex: http://stony-sport4u.de

**Comment by diddipoeler** [comment]
many thanks sigal.

**Comment by diddipoeler** [comment]
Please make your translation on Transifex!

**Pull request closed without merging**
